---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: staging
spec:
  selector:
    matchLabels:
      run: php-apache
  # remove replica if using gitops
  # replicas: 1
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
        - name: php-apache
          image: lank8s.cn/hpa-example
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 180m
              memory: 256Mi
            requests:
              cpu: 180m
              memory: 256Mi